name: Vercel Build

description: Build to deploy to Vercel

inputs:
  project_name:
    description: "The working directory/project name you're trying to build. Example: 'www', 'blog'"
    required: true
  NODE_ENV:
    description: ""
    required: true
  VERCEL_TOKEN:
    description: "Vercel token for authentication"
    required: true
  VERCEL_ORG_ID:
    description: "Vercel organization ID"
    required: true
  VERCEL_PROJECT_ID:
    description: "Vercel project ID"
    required: true
  NEXT_PUBLIC_WWW_URL:
    description: ""
    required: true
  NEXT_PUBLIC_BLOG_URL:
    description: ""
    required: true
  NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID:
    description: ""
    required: true
  NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID:
    description: ""
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/pnpm-install
    - uses: ./.github/actions/setup-env
      with:
        NODE_ENV: ${{ inputs.NODE_ENV }}
        NEXT_PUBLIC_WWW_URL: ${{ inputs.NEXT_PUBLIC_WWW_URL }}
        NEXT_PUBLIC_BLOG_URL: ${{ inputs.NEXT_PUBLIC_BLOG_URL }}
        NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID: ${{ inputs.NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID }}
        NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID: ${{ inputs.NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID }}

    - name: Debug Environment Variables
      shell: bash
      run: |
        echo "NEXT_PUBLIC_WWW_URL: ${{ inputs.NEXT_PUBLIC_WWW_URL }}"
        echo "NEXT_PUBLIC_BLOG_URL: ${{ inputs.NEXT_PUBLIC_BLOG_URL }}"
        echo "NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID: ${{ inputs.NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID }}"
        echo "NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID: ${{ inputs.NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID }}"

    - name: Set Env Vars on Vercel Project
      uses: dkershner6/vercel-set-env-action@v3
      env:
        ENV_NEXT_PUBLIC_WWW_URL: ${{ inputs.NEXT_PUBLIC_WWW_URL }}
        TARGET_NEXT_PUBLIC_WWW_URL: ${{ inputs.NODE_ENV }}
        TYPE_NEXT_PUBLIC_WWW_URL: plain

        ENV_NEXT_PUBLIC_BLOG_URL: ${{ inputs.NEXT_PUBLIC_BLOG_URL }}
        TARGET_NEXT_PUBLIC_BLOG_URL: ${{ inputs.NODE_ENV }}
        TYPE_NEXT_PUBLIC_BLOG_URL: plain

        ENV_NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID: ${{ inputs.NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID }}
        TARGET_NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID: ${{ inputs.NODE_ENV }}
        TYPE_NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID: plain

        ENV_NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID: ${{ inputs.NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID }}
        TARGET_NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID: ${{ inputs.NODE_ENV }}
        TYPE_NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID: plain

      with:
        token: ${{ inputs.VERCEL_TOKEN }}
        teamId: ${{ inputs.VERCEL_ORG_ID }}
        projectName: ${{ inputs.project_name }}
        envVariableKeys: NEXT_PUBLIC_WWW_URL,NEXT_PUBLIC_BLOG_URL,NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID,NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID

    - name: Build for Vercel
      shell: bash
      env:
        VERCEL_TOKEN: ${{ inputs.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ inputs.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ inputs.VERCEL_PROJECT_ID }}
      run: |
        cd apps/${{ inputs.project_name }} && pnpm --filter @ashgw/${{ inputs.project_name }} build:vercel --token=$VERCEL_TOKEN
