name: "Setup Environment Variables"
description: "Sets up env from GitHub Secrets"
inputs:
  NEXT_PUBLIC_WWW_URL:
    required: true
  NEXT_PUBLIC_BLOG_URL:
    required: true
  NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID:
    required: true
  NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID:
    required: true
runs:
  using: composite
  steps:
    - name: Set up .env
      shell: bash
      run: |
        vars=(
          "NEXT_PUBLIC_WWW_URL"
          "NEXT_PUBLIC_BLOG_URL"
          "NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID"
          "NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID"
        )
        for var in "${vars[@]}"; do
          echo "$var='${{ inputs[$var] }}'" >> .env
        done
