name: CI / Blog preview deployment

on:
  workflow_call:

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  deploy:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/vercel-build
        with:
          ENV_VARS: ${{ secrets.ENV_VARS }}
          GA_ID: ${{ secrets.GA_ID }}
          project_name: blog
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BLOG_PROJECT_ID }}
      - uses: ./.github/actions/vercel-deploy
        with:
          project_name: blog
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
