name: CI

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: ./.github/actions/pnpm-install
      - uses: ./.github/actions/setup-env
        with:
          ENV_VARS: ${{ secrets.ENV_VARS }}
          GA_ID: ${{ secrets.GA_ID }}
      - name: build
        shell: bash
        run: pnpm build
