name: CI

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          env_vars: ${{ secrets.ENV_VARS }}
          ga_id: ${{ secrets.GA_ID }}
