name: Production Deployment

on:
  workflow_dispatch:
  workflow_call:

# This is merely used as a trigger here so I can manually dispatch all prod deployments
jobs:
  deploy-production:
    if: github.ref == 'refs/heads/main'
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        id: all-green
        with:
          jobs: ${{ toJSON(needs) }}
